# Generated by Django 3.1.4 on 2020-12-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_links_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='name',
            new_name='link_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='sub_category_name',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='chatbot.category'),
        ),
    ]
