# Generated by Django 3.1.4 on 2020-12-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20201206_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['link_name']},
        ),
    ]
